version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "8081:8081"
  
  backend:
    build:
      context: ./ApiNode
    ports:
      - "8080:8080"
  
  mobile:
    build:
      context: ./area_mobile
