// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9FKwoncTFAzUhqnkbBzeQ2NWGzlTWt_E',
    appId: '1:544176690050:android:09a605319722e87534f59b',
    messagingSenderId: '544176690050',
    projectId: 'area-8b6d2',
    storageBucket: 'area-8b6d2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2smhKFN2DAopsZfnOJdrliju_5v3G5bg',
    appId: '1:544176690050:ios:a40de5c8f99418d234f59b',
    messagingSenderId: '544176690050',
    projectId: 'area-8b6d2',
    storageBucket: 'area-8b6d2.appspot.com',
    iosBundleId: 'com.example.areaMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2smhKFN2DAopsZfnOJdrliju_5v3G5bg',
    appId: '1:544176690050:ios:a40de5c8f99418d234f59b',
    messagingSenderId: '544176690050',
    projectId: 'area-8b6d2',
    storageBucket: 'area-8b6d2.appspot.com',
    iosBundleId: 'com.example.areaMobile',
  );
}
